development:
  env_name: <%= ENV["ENV_NAME"] %>
  build_number: <%= ENV["BUILD_NUMBER"] %>
  commit_sha: <%= ENV["COMMIT_SHA"] %>
  secret_key_base: ce4c380da77f36f967964c4272cda0e0b758ff2fca76829830b6e2173e700b0372ac80100095dd6ca58abbda90b192d6dbe32f50d6fe7ca7a8a74975bee6711e
  user_endpoint: <%= ENV.fetch('USER_ENDPOINT', 'http://localhost:3010/resources') %>
  user_token: <%= ENV.fetch('USER_TOKEN', 'DEFAULT_TOKEN') %>
  marketplace_endpoint: <%= ENV.fetch('MARKETPLACE_ENDPOINT', 'http://localhost:9090/resources') %>
  marketplace_token: <%= ENV.fetch('MARKETPLACE_TOKEN', 'DEFAULT_TOKEN') %>
  allowed_origins: <%= ENV.fetch('ALLOWED_ORIGINS', 'http://84f9dce6.ngrok.io') %> # In case you want multiple domains, just separe them with a comma (but do it in the .env file!)
  hostname: <%= ENV.fetch('ALLOWED_ORIGINS', 'http://84f9dce6.ngrok.io') %>
  base_url: <%= ENV.fetch('TIKO_LOGISTICS_API_URL') %>
  redis_host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
  redis_port: <%= ENV.fetch('REDIS_PORT', '6379') %>
  redis_db: <%= ENV.fetch('REDIS_DB', '2') %>
  sentry_dsn: <%= ENV.fetch('SENTRY_DSN', '') %>
  aws_region: <%= ENV.fetch('AWS_REGION', 'us-east-1') %>
  aws_sns_arn_android: <%= ENV.fetch('AWS_SNS_ARN_ANDROID', 'asdf') %>
  firebase_token: <%= ENV.fetch("FIREBASE_TOKEN", 'AIzaSyC_diHZLXFrKziGSDs2tt6qHQGgtxWN8oc ') %>
  firebase_token_shippers: <%= ENV.fetch("FIREBASE_TOKEN_SHIPPERS", '') %>

  paypal_client_id: <%= ENV.fetch('PAYPAL_CLIENT_ID', 'AVySA_SJfyFHZYJ2VaTkvOjfGR88BTi0JciutS2aSj0j9ljnG2ijGBJOYjsyFUvuykrS1x4aIUUOk8ZV') %>
  paypal_client_secret: <%= ENV.fetch('PAYPAL_CLIENT_SECRET', 'ENbvE6_iKIvlfImVZHDDj-e07gpc78P48d8pJzPpZpQ7S9QFr5mxJZQ9FZbmYdp0x7qbyvR1oiPtbBRO') %>

  scheduler_url: <%= ENV.fetch('SCHEDULER_URL', 'http://localhost:8080') %>
  scheduler_token: <%= ENV.fetch('SCHEDULER_TOKEN', 'nilus_logistic') %>

  job_token: <%= ENV.fetch('JOB_TOKEN', 'token') %>
  job_endpoint: <%= ENV.fetch('JOB_ENDPOINT', 'http://localhost:3030') %>

  gmap_api_key: <%= ENV.fetch('GOOGLE_API_KEY','XXXX') %>

  cors_origins: <%= ENV.fetch('CORS_ORIGINS', 'http://staging.tikoglobal.com, http://marketplace-staging.tikoglobal.com, http://sellers-staging.tikoglobal.com, http://localhost:3010, http://localhost:9090') %>

  fix_rate: <%= ENV.fetch('FIX_RATE','50') %>
  rate_per_mile: <%= ENV.fetch('RATE_PER_MILE','4') %>
  rate_per_tone: <%= ENV.fetch('RATE_PER_TONE','50') %>
  insurance_rate: <%= ENV.fetch('INSURANCE_RATE','1') %>
  default_delivery_cost: <%= ENV.fetch('DEFAULT_DELIVERY_COST','133.33') %>

  aws_access_key_id: <%= ENV.fetch('AWS_ACCESS_KEY_ID') %>
  aws_secret_access_key: <%= ENV.fetch('AWS_SECRET_ACCESS_KEY') %>
  aws_default_media_bucket: <%= ENV.fetch('AWS_DEFAULT_MEDIA_BUCKET') %>

  notification_email_username: <%= ENV['NOTIFICATION_EMAIL_USERNAME'] %>
  notification_email_password: <%= ENV['NOTIFICATION_EMAIL_PASSWORD'] %>
  notification_email_domain: <%= ENV['NOTIFICATION_EMAIL_DOMAIN'] %>
  notification_email_address: <%= ENV['NOTIFICATION_EMAIL_ADDRESS'] %>
  tiko_employees_email: <%= ENV.fetch('TIKO_EMPLOYEES_EMAIL') %>
  tiko_notification_email: <%= ENV.fetch('TIKO_NOTIFICATION_EMAIL') %>
  tiko_notification_email_name: <%= ENV.fetch('TIKO_NOTIFICATION_EMAIL_NAME') %>
  tiko_logistics_email: <%= ENV.fetch('TIKO_LOGISTICS_EMAIL') %>
  tiko_logistics_email_name: <%= ENV.fetch('TIKO_LOGISTICS_EMAIL_NAME') %>
  tiko_bbc_from_email: <%= ENV.fetch('TIKO_BBC_FROM_EMAIL') %>

  smtp_user_name: <%= ENV.fetch('SMTP_USER_NAME') %>
  smtp_password: <%= ENV.fetch('SMTP_PASSWORD') %>
  smtp_address: <%= ENV.fetch('SMTP_ADDRESS') %>
  smtp_domain: <%= ENV.fetch('SMTP_DOMAIN') %>
  smtp_authentication: <%= ENV.fetch('SMTP_AUTHENTICATION') %>
  smtp_port: <%= ENV.fetch('SMTP_PORT') %>

  tiko_backoffice_app: <%= ENV.fetch('TIKO_BACKOFFICE_APP', 'http://localhost:3000') %>
  tiko_drivers_app: <%= ENV.fetch('TIKO_DRIVERS_APP', 'tiko-drivers-app://http://localhost:9091') %>

  storage_service: <%= ENV.fetch('STORAGE_SERVICE', 'local') %>

  app_dynamic_link: <%= ENV.fetch('APP_DYNAMIC_LINK', 'https://tikoglobal.page.link') %>
  app_redirect_link: <%= ENV.fetch('APP_REDIRECT_LINK', 'https://drivers.tikoglobal.com') %>
  app_desktop_link: <%= ENV.fetch('APP_DESKTOP_LINK', 'https://drivers.tikoglobal.com') %>
  firebase_dynamic_link_apn: <%= ENV.fetch('FIREBASE_DYNAMIC_LINK_APN', 'com.tikoglobal.drivers') %>
  firebase_dynamic_link_isi: <%= ENV.fetch('FIREBASE_DYNAMIC_LINK_ISI', '1518272922') %>
  firebase_dynamic_link_ibi: <%= ENV.fetch('FIREBASE_DYNAMIC_LINK_IBI', 'com.tikoglobal.drivers') %>

test: &test
  env_name: <%= ENV["ENV_NAME"] %>
  build_number: <%= ENV["BUILD_NUMBER"] %>
  commit_sha: <%= ENV["COMMIT_SHA"] %>
  secret_key_base: 25195f1d108b33e588ab69b9f2c2f848f676a453f39b0b99671845fb25dfd3cd8feeaa10bba5f59d6dbf636ade7657fc356ff9cdabff19ca7ec694311abbc341
  user_endpoint: <%= ENV.fetch('USER_ENDPOINT', 'http://localhost:3010/resources') %>
  user_token: <%= ENV.fetch('USER_TOKEN', 'DEFAULT_TOKEN') %>
  marketplace_endpoint: <%= ENV.fetch('MARKETPLACE_ENDPOINT', 'http://localhost:9090/resources') %>
  marketplace_token: <%= ENV.fetch('MARKETPLACE_TOKEN', 'DEFAULT_TOKEN') %>
  allowed_origins: <%= ENV.fetch('ALLOWED_ORIGINS', 'localhost:3000') %> # In case you want multiple domains, just separe them with a comma (but do it in the .env file!)
  hostname: <%= ENV.fetch('ALLOWED_ORIGINS', 'localhost') %>
  base_url: <%= ENV.fetch('TIKO_LOGISTICS_API_URL') %>
  redis_host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
  redis_port: <%= ENV.fetch('REDIS_PORT', '6379') %>
  redis_db: <%= ENV.fetch('REDIS_DB', '2') %>
  sentry_dsn: <%= ENV.fetch('SENTRY_DSN', '') %>
  aws_region: <%= ENV.fetch('AWS_REGION', 'us-east-1') %>
  aws_sns_arn_android: <%= ENV.fetch('AWS_SNS_ARN_ANDROID', '') %>
  firebase_token: <%= ENV.fetch("FIREBASE_TOKEN", '') %>
  firebase_token_shippers: <%= ENV.fetch("FIREBASE_TOKEN_SHIPPERS", '') %>

  paypal_client_id: <%= ENV.fetch('PAYPAL_CLIENT_ID', 'AVySA_SJfyFHZYJ2VaTkvOjfGR88BTi0JciutS2aSj0j9ljnG2ijGBJOYjsyFUvuykrS1x4aIUUOk8ZV') %>
  paypal_client_secret: <%= ENV.fetch('PAYPAL_CLIENT_SECRET', 'ENbvE6_iKIvlfImVZHDDj-e07gpc78P48d8pJzPpZpQ7S9QFr5mxJZQ9FZbmYdp0x7qbyvR1oiPtbBRO') %>

  scheduler_url: <%= ENV.fetch('SCHEDULER_URL', 'http://localhost:8080') %>
  scheduler_token: <%= ENV.fetch('SCHEDULER_TOKEN', 'nilus_logistic') %>

  job_token: <%= ENV.fetch('JOB_TOKEN', 'token') %>
  job_endpoint: <%= ENV.fetch('JOB_ENDPOINT', 'http://localhost:3030') %>

  cors_origins: <%= ENV.fetch('CORS_ORIGINS') %>

  fix_rate: <%= ENV.fetch('FIX_RATE','50') %>
  rate_per_mile: <%= ENV.fetch('RATE_PER_MILE','4') %>
  rate_per_tone: <%= ENV.fetch('RATE_PER_TONE','50') %>
  insurance_rate: <%= ENV.fetch('INSURANCE_RATE','1') %>
  default_delivery_cost: <%= ENV.fetch('DEFAULT_DELIVERY_COST','133.33') %>

  aws_access_key_id: <%= ENV.fetch('AWS_ACCESS_KEY_ID') %>
  aws_secret_access_key: <%= ENV.fetch('AWS_SECRET_ACCESS_KEY') %>
  aws_default_media_bucket: <%= ENV.fetch('AWS_DEFAULT_MEDIA_BUCKET') %>

  notification_email_username: <%= ENV['NOTIFICATION_EMAIL_USERNAME'] %>
  notification_email_password: <%= ENV['NOTIFICATION_EMAIL_PASSWORD'] %>
  notification_email_domain: <%= ENV['NOTIFICATION_EMAIL_DOMAIN'] %>
  notification_email_address: <%= ENV['NOTIFICATION_EMAIL_ADDRESS'] %>
  tiko_employees_email: <%= ENV.fetch('TIKO_EMPLOYEES_EMAIL') %>
  tiko_notification_email: <%= ENV.fetch('TIKO_NOTIFICATION_EMAIL') %>
  tiko_notification_email_name: <%= ENV.fetch('TIKO_NOTIFICATION_EMAIL_NAME') %>
  tiko_logistics_email: <%= ENV.fetch('TIKO_LOGISTICS_EMAIL') %>
  tiko_logistics_email_name: <%= ENV.fetch('TIKO_LOGISTICS_EMAIL_NAME') %>
  tiko_bbc_from_email: <%= ENV.fetch('TIKO_BBC_FROM_EMAIL') %>

  smtp_user_name: <%= ENV.fetch('SMTP_USER_NAME') %>
  smtp_password: <%= ENV.fetch('SMTP_PASSWORD') %>
  smtp_address: <%= ENV.fetch('SMTP_ADDRESS') %>
  smtp_domain: <%= ENV.fetch('SMTP_DOMAIN') %>
  smtp_authentication: <%= ENV.fetch('SMTP_AUTHENTICATION') %>
  smtp_port: <%= ENV.fetch('SMTP_PORT') %>

  tiko_backoffice_app: <%= ENV.fetch('TIKO_BACKOFFICE_APP', 'http://localhost:3000') %>
  tiko_drivers_app: <%= ENV.fetch('TIKO_DRIVERS_APP', 'tiko-drivers-app://http://localhost:9091') %>

  storage_service: <%= ENV.fetch('STORAGE_SERVICE', 'local') %>

  app_dynamic_link: <%= ENV.fetch('APP_DYNAMIC_LINK', 'https://tikoglobal.page.link') %>
  app_redirect_link: <%= ENV.fetch('APP_REDIRECT_LINK', 'https://drivers.tikoglobal.com') %>
  app_desktop_link: <%= ENV.fetch('APP_DESKTOP_LINK', 'https://drivers.tikoglobal.com') %>
  firebase_dynamic_link_apn: <%= ENV.fetch('FIREBASE_DYNAMIC_LINK_APN', 'com.tikoglobal.drivers') %>
  firebase_dynamic_link_isi: <%= ENV.fetch('FIREBASE_DYNAMIC_LINK_ISI', '1518272922') %>
  firebase_dynamic_link_ibi: <%= ENV.fetch('FIREBASE_DYNAMIC_LINK_IBI', 'com.tikoglobal.drivers') %>

cypress:
  <<: *test

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  env_name: <%= ENV["ENV_NAME"] %>
  build_number: <%= ENV["BUILD_NUMBER"] %>
  commit_sha: <%= ENV["COMMIT_SHA"] %>
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
  user_endpoint: <%= ENV.fetch('USER_ENDPOINT', 'http://localhost:3010/resources') %>
  user_token: <%= ENV.fetch('USER_TOKEN', 'DEFAULT_TOKEN') %>
  marketplace_endpoint: <%= ENV.fetch('MARKETPLACE_ENDPOINT', 'http://localhost:9090/resources') %>
  marketplace_token: <%= ENV.fetch('MARKETPLACE_TOKEN', 'DEFAULT_TOKEN') %>
  allowed_origins: <%= ENV.fetch('ALLOWED_ORIGINS', 'localhost:3000') %> # In case you want multiple domains, just separe them with a comma (but do it in the .env file!)
  hostname: <%= ENV.fetch('ALLOWED_ORIGINS', 'localhost:3030') %>
  base_url: <%= ENV.fetch('TIKO_LOGISTICS_API_URL') %>
  redis_host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
  redis_port: <%= ENV.fetch('REDIS_PORT', '6379') %>
  redis_db: <%= ENV.fetch('REDIS_DB', '2') %>
  sentry_dsn: <%= ENV.fetch('SENTRY_DSN', '') %>
  aws_region: <%= ENV.fetch('AWS_REGION', 'aToken') %>
  aws_sns_arn_android: <%= ENV.fetch('AWS_SNS_ARN_ANDROID', 'aToken') %>
  firebase_token: <%= ENV.fetch("FIREBASE_TOKEN", '') %>
  firebase_token_shippers: <%= ENV.fetch("FIREBASE_TOKEN_SHIPPERS", '') %>

  paypal_client_id: <%= ENV.fetch('PAYPAL_CLIENT_ID', 'AVySA_SJfyFHZYJ2VaTkvOjfGR88BTi0JciutS2aSj0j9ljnG2ijGBJOYjsyFUvuykrS1x4aIUUOk8ZV') %>
  paypal_client_secret: <%= ENV.fetch('PAYPAL_CLIENT_SECRET', 'ENbvE6_iKIvlfImVZHDDj-e07gpc78P48d8pJzPpZpQ7S9QFr5mxJZQ9FZbmYdp0x7qbyvR1oiPtbBRO') %>

  scheduler_url: <%= ENV.fetch('SCHEDULER_URL', 'aToken') %>
  scheduler_token: <%= ENV.fetch('SCHEDULER_TOKEN', 'aToken') %>

  job_token: <%= ENV.fetch('JOB_TOKEN', 'aToken') %>
  job_endpoint: <%= ENV.fetch('JOB_ENDPOINT', 'aToken') %>

  gmap_api_key: <%= ENV.fetch('GOOGLE_API_KEY','xxxx') %>

  cors_origins: <%= ENV.fetch('CORS_ORIGINS') %>

  fix_rate: <%= ENV.fetch('FIX_RATE','50') %>
  rate_per_mile: <%= ENV.fetch('RATE_PER_MILE','4') %>
  rate_per_tone: <%= ENV.fetch('RATE_PER_TONE','50') %>
  insurance_rate: <%= ENV.fetch('INSURANCE_RATE','1') %>
  default_delivery_cost: <%= ENV.fetch('DEFAULT_DELIVERY_COST','133.33') %>

  aws_access_key_id: <%= ENV.fetch('AWS_ACCESS_KEY_ID') %>
  aws_secret_access_key: <%= ENV.fetch('AWS_SECRET_ACCESS_KEY') %>
  aws_default_media_bucket: <%= ENV.fetch('AWS_DEFAULT_MEDIA_BUCKET') %>

  notification_email_username: <%= ENV['NOTIFICATION_EMAIL_USERNAME'] %>
  notification_email_password: <%= ENV['NOTIFICATION_EMAIL_PASSWORD'] %>
  notification_email_domain: <%= ENV['NOTIFICATION_EMAIL_DOMAIN'] %>
  notification_email_address: <%= ENV['NOTIFICATION_EMAIL_ADDRESS'] %>
  tiko_employees_email: <%= ENV.fetch('TIKO_EMPLOYEES_EMAIL') %>
  tiko_notification_email: <%= ENV.fetch('TIKO_NOTIFICATION_EMAIL') %>
  tiko_notification_email_name: <%= ENV.fetch('TIKO_NOTIFICATION_EMAIL_NAME') %>
  tiko_logistics_email: <%= ENV.fetch('TIKO_LOGISTICS_EMAIL') %>
  tiko_logistics_email_name: <%= ENV.fetch('TIKO_LOGISTICS_EMAIL_NAME') %>
  tiko_bbc_from_email: <%= ENV.fetch('TIKO_BBC_FROM_EMAIL') %>

  smtp_user_name: <%= ENV.fetch('SMTP_USER_NAME') %>
  smtp_password: <%= ENV.fetch('SMTP_PASSWORD') %>
  smtp_address: <%= ENV.fetch('SMTP_ADDRESS') %>
  smtp_domain: <%= ENV.fetch('SMTP_DOMAIN') %>
  smtp_authentication: <%= ENV.fetch('SMTP_AUTHENTICATION') %>
  smtp_port: <%= ENV.fetch('SMTP_PORT') %>

  tiko_backoffice_app: <%= ENV.fetch('TIKO_BACKOFFICE_APP', 'http://localhost:3000') %>
  tiko_drivers_app: <%= ENV.fetch('TIKO_DRIVERS_APP', 'tiko-drivers-app://http://localhost:9091') %>

  storage_service: <%= ENV.fetch('STORAGE_SERVICE', 'local') %>

  app_dynamic_link: <%= ENV.fetch('APP_DYNAMIC_LINK', 'https://tikoglobal.page.link') %>
  app_redirect_link: <%= ENV.fetch('APP_REDIRECT_LINK', 'https://drivers.tikoglobal.com') %>
  app_desktop_link: <%= ENV.fetch('APP_DESKTOP_LINK', 'https://drivers.tikoglobal.com') %>
  firebase_dynamic_link_apn: <%= ENV.fetch('FIREBASE_DYNAMIC_LINK_APN', 'com.tikoglobal.drivers') %>
  firebase_dynamic_link_isi: <%= ENV.fetch('FIREBASE_DYNAMIC_LINK_ISI', '1518272922') %>
  firebase_dynamic_link_ibi: <%= ENV.fetch('FIREBASE_DYNAMIC_LINK_IBI', 'com.tikoglobal.drivers') %>
